// Captions for each letter video
export const captions = {
    a: "A - Robots are <strong>afraid</strong> of the dark",
    b: "B - Look at my new <strong>belly button</strong>",
    c: "C - Robots can hug a <strong>cactus</strong>",
    d: "D - I want to <strong>dance</strong> the robot boogie",
    e: "E - <strong>Electronics</strong> (it's hard for me to say that)",
    f: "F - Robots can <strong>fly</strong>",
    g: "G - Do you like my <strong>goggles?</strong>",
    h: "H - Robots can get <strong>hiccups</strong>",
    i: "I - I want to go in <strong>IKEA</strong>",
    j: "J - Robots can't jump very <strong>high</strong>",
    k: "K - Robots can help in the <strong>kitchen</strong>",
    l: "L - Robots get <strong>lonely</strong>",
    m: "M - Robots aren't scared of <strong>monsters</strong>",
    n: "N - Robots appreciate <strong>nature</strong> and beauty",
    o: "O - I'm scared of that <strong>octopus</strong>",
    p: "P - Let's throw a <strong>party</strong> at the space noodle",
    q: "Q - Robots <strong>question</strong> and seek understanding",
    r: "R - I am a <strong>robot</strong>",
    s: "S - Robots can eat <strong>soup</strong>",
    t: "T - Something is wrong with my <strong>tummy</strong>",
    u: "U - Robots believe in <strong>unity</strong> and togetherness",
    v: "V - I used to be a <strong>vacuum</strong>",
    w: "W - Robots <strong>wonder</strong> and marvel at the world",
    x: "X - This is what I look like in <strong>x-ray</strong>",
    y: "Y - I'm sorry <strong>Yoshimi</strong>",
    z: "Z - I wish I had a <strong>zeppelin</strong>"
};
