// Captions for each letter video
// Replace these placeholder texts with your actual captions
export const captions = {
    a: "A - Robots are <b>afraid</b> of the dark",
    b: "B - Look at my new <b>belly button</b>",
    c: "C - Robots can hug a <b>cactus</b>",
    d: "D - I want to <b>dance</b> the robot boogie",
    e: "E - <b>Electronics</b> (it's hard for me to say that))",
    f: "F - Robots can fly <b>fly</b>",
    g: "G - Do you like my <b>goggles?</b>",
    h: "H - Robots can get <b>hiccups</b>",
    i: "I - I want to go in <b>IKEA</b>",
    j: "J - Robots can't jump very <b>high</b>",
    k: "K is for Kindness - spread it everywhere",
    l: "L is for Learn - something new always",
    m: "M is for Magic - in everyday moments",
    n: "N is for Nature - beauty all around",
    o: "O is for Opportunity - seize the day",
    p: "P is for Passion - pursue what you love",
    q: "Q is for Question - seek understanding",
    r: "R is for Resilience - bounce back stronger",
    s: "S - Robots can <b>Smile</b> - brighten someone's day",
    t: "T - Robots can <b>Transform</b> - become your best self",
    u: "U - Robots can <b>Unity</b> - together we're stronger",
    v: "V - Robots can <b>Vision</b> - see the possibilities",
    w: "W - Robots can <b>Wonder</b> - marvel at the world",
    x: "X - Robots can <b>eXcellence</b> - strive for greatness",
    y: "Y - Robots can <b>Yes</b> - say yes to new experiences",
    z: "Z - Robots can <b>Zest</b> - live life with enthusiasm"
};
