// Captions for each letter video
export const captions = {
    hint: "Press any letter key (A-Z) to play",
    hintMobile: "Tap here to start",
    a: "A - Robots are <strong>AFRAID</strong> of the dark",
    b: "B - Look at my new <strong>BELLY BUTTON</strong>",
    c: "C - Robots can hug a <strong>CACTUS</strong>",
    d: "D - I want to <strong>DANCE</strong>",
    e: "E - <strong>ELECTRONICS</strong> (hard for me to say)",
    f: "F - Robots can <strong>FLY</strong>",
    g: "G - Do you like my <strong>GOGGLES?</strong>",
    h: "H - Robots can get <strong>HICCUPS</strong>",
    i: "I - I want to go in <strong>IKEA</strong>",
    j: "J - Robots can't <strong>JUMP</strong> very high",
    k: "K - Robots can help in the <strong>KITCHEN</strong>",
    l: "L - Robots get <strong>LONELY</strong>",
    m: "M - Robots aren't scared of <strong>MONSTERS</strong>",
    n: "N - <strong>NOTHING</strong> is happening",
    o: "O - I'm scared of that <strong>OCTOPUS</strong>",
    p: "P - Let's have a <strong>PARTY</strong>",
    q: "Q - It's hard for robots to be <strong>QUIET</strong>",
    r: "R - I am a <strong>ROBOT</strong>",
    s: "S - Robots can eat <strong>SOUP</strong>",
    t: "T - Something is wrong with my <strong>TUMMY</strong>",
    u: "U - Robots can hang <strong>UPSIDE-DOWN</strong>",
    v: "V - I used to be a <strong>VACUUM</strong>",
    w: "W - Robots freeze in the <strong>WINTER</strong>",
    x: "X - This is what I look like in <strong>X-RAY</strong>",
    y: "Y - I'm sorry <strong>YOSHIMI</strong>",
    z: "Z - I wish I had a <strong>ZEPPELIN</strong>",
    space: "_ - <strong>SPACE</strong> is boring"
};
